backend:
  name: github
  repo: hendrywu2020/010news
  branch: master
  auth_type: pkce-implicit  # 使用更安全的 PKCE 方式
  app_id: Ov231iDD2cc4TjIsmKnn
  base_url: https://010news.pages.dev

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "文章"
    folder: "content/posts"
    create: true
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - { label: "內文", name: "body", widget: "markdown" }